# Generated by Django 4.1.4 on 2022-12-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('exec_by', models.CharField(max_length=255)),
                ('cost', models.FloatField()),
                ('timespan', models.CharField(max_length=255)),
                ('project_id', models.CharField(max_length=255)),
                ('goal', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('completion', models.FloatField()),
                ('actual_cost', models.FloatField()),
            ],
        ),
    ]
