# Generated by Django 4.1.4 on 2022-12-20 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Constraints', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constraints',
            options={'verbose_name_plural': 'Constraints'},
        ),
    ]
